# Generated by Django 2.2 on 2019-05-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
